### ISSUE TITLE
Met Some Problem When Building Code in Visual Studio 2022(Community)

### ISSUE THREAD

**Issue by fbdxl** [TeomanDeniz/ft_math#4]
Hi Mr. Deniz

I was trying to build your code into a lib so that I can use it in MATLAB.

The compile tool I was using is Visual Studio 2022 community version. But after compiling, The VS2022 reported so many errors which I attached below. 

Do you know Why I got those problems? Did you compile these code in visual studio environment before?

Wish to get your reply, Thank you very much!

**Comment by fbdxl** [comment]
![Uploading VS2022_building_error.png…]()

**Comment by TeomanDeniz** [comment]
There is indeed compiling errors on the project. Thanks for reporting that and I am apologize for late response. The errors are fixed now.
